/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more.
 *
 * The version of the OpenAPI document: v1.3.8
 * Contact: office@ory.sh
 * Generated by: https://openapi-generator.tech
 */
use super::{AddQuery, Error, configuration};
use crate::{models, wasm_apis::ResponseContent};
use gloo_utils::format::JsValueSerdeExt;
use serde::{Deserialize, Serialize};
use wasm_bindgen::prelude::*;
use wasm_bindgen_futures::JsFuture;
use web_sys::{Request, RequestCredentials, RequestInit, RequestMode, Response};

/// struct for typed errors of method [`batch_patch_identities`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BatchPatchIdentitiesError {
    Status400(models::ErrorGeneric),
    Status409(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_identity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateIdentityError {
    Status400(models::ErrorGeneric),
    Status409(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_recovery_code_for_identity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateRecoveryCodeForIdentityError {
    Status400(models::ErrorGeneric),
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_recovery_link_for_identity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateRecoveryLinkForIdentityError {
    Status400(models::ErrorGeneric),
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_identity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteIdentityError {
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_identity_credentials`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteIdentityCredentialsError {
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_identity_sessions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteIdentitySessionsError {
    Status400(models::ErrorGeneric),
    Status401(models::ErrorGeneric),
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`disable_session`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DisableSessionError {
    Status400(models::ErrorGeneric),
    Status401(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`extend_session`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExtendSessionError {
    Status400(models::ErrorGeneric),
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_identity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetIdentityError {
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_identity_schema`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetIdentitySchemaError {
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_session`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSessionError {
    Status400(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_identities`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListIdentitiesError {
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_identity_schemas`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListIdentitySchemasError {
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_identity_sessions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListIdentitySessionsError {
    Status400(models::ErrorGeneric),
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_sessions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListSessionsError {
    Status400(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`patch_identity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PatchIdentityError {
    Status400(models::ErrorGeneric),
    Status404(models::ErrorGeneric),
    Status409(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_identity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateIdentityError {
    Status400(models::ErrorGeneric),
    Status404(models::ErrorGeneric),
    Status409(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// Creates multiple [identities](https://www.ory.sh/docs/kratos/concepts/identity-user-model). This endpoint can also be used to [import credentials](https://www.ory.sh/docs/kratos/manage-identities/import-user-accounts-identities) for instance passwords, social sign in configurations or multifactor methods.
pub async fn batch_patch_identities(
    configuration: &configuration::Configuration,
    patch_identities_body: Option<models::PatchIdentitiesBody>,
) -> Result<models::BatchPatchIdentitiesResponse, Error<BatchPatchIdentitiesError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("PATCH");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let possible_uri_len = configuration.base_path.len() + "/admin/identities".len();
    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities");

    client.set_body(&JsValue::from_serde(&patch_identities_body)?);

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;
    req_builder
        .headers()
        .set("Content-Type", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        content.into_serde().map_err(Error::from)
    } else {
        let entity: Option<BatchPatchIdentitiesError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// Create an [identity](https://www.ory.sh/docs/kratos/concepts/identity-user-model).  This endpoint can also be used to [import credentials](https://www.ory.sh/docs/kratos/manage-identities/import-user-accounts-identities) for instance passwords, social sign in configurations or multifactor methods.
pub async fn create_identity(
    configuration: &configuration::Configuration,
    create_identity_body: Option<models::CreateIdentityBody>,
) -> Result<models::Identity, Error<CreateIdentityError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("POST");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let possible_uri_len = configuration.base_path.len() + "/admin/identities".len();
    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities");

    client.set_body(&JsValue::from_serde(&create_identity_body)?);

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;
    req_builder
        .headers()
        .set("Content-Type", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        content.into_serde().map_err(Error::from)
    } else {
        let entity: Option<CreateIdentityError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// This endpoint creates a recovery code which should be given to the user in order for them to recover (or activate) their account.
pub async fn create_recovery_code_for_identity(
    configuration: &configuration::Configuration,
    create_recovery_code_for_identity_body: Option<models::CreateRecoveryCodeForIdentityBody>,
) -> Result<models::RecoveryCodeForIdentity, Error<CreateRecoveryCodeForIdentityError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("POST");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let possible_uri_len = configuration.base_path.len() + "/admin/recovery/code".len();
    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/recovery/code");

    client.set_body(&JsValue::from_serde(
        &create_recovery_code_for_identity_body,
    )?);

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;
    req_builder
        .headers()
        .set("Content-Type", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        content.into_serde().map_err(Error::from)
    } else {
        let entity: Option<CreateRecoveryCodeForIdentityError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// This endpoint creates a recovery link which should be given to the user in order for them to recover (or activate) their account.
pub async fn create_recovery_link_for_identity(
    configuration: &configuration::Configuration,
    return_to: Option<&str>,
    create_recovery_link_for_identity_body: Option<models::CreateRecoveryLinkForIdentityBody>,
) -> Result<models::RecoveryLinkForIdentity, Error<CreateRecoveryLinkForIdentityError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("POST");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let possible_uri_len =
        (configuration.base_path.len() * 2) + "/admin/recovery/link".len() + "?return_to=".len();
    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/recovery/link");

    if let Some(ref str) = return_to {
        uri_str.push_str("?return_to=");
        uri_str.push_str(&str);
    }

    client.set_body(&JsValue::from_serde(
        &create_recovery_link_for_identity_body,
    )?);

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;
    req_builder
        .headers()
        .set("Content-Type", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        content.into_serde().map_err(Error::from)
    } else {
        let entity: Option<CreateRecoveryLinkForIdentityError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// Calling this endpoint irrecoverably and permanently deletes the [identity](https://www.ory.sh/docs/kratos/concepts/identity-user-model) given its ID. This action can not be undone. This endpoint returns 204 when the identity was deleted or when the identity was not found, in which case it is assumed that is has been deleted already.
pub async fn delete_identity(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<(), Error<DeleteIdentityError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("DELETE");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let id = crate::wasm_apis::urlencode(id);
    let possible_uri_len = configuration.base_path.len() + "/admin/identities/".len() + id.len();

    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities/");
    uri_str.push_str(&id);

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        Ok(())
    } else {
        let entity: Option<DeleteIdentityError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// Delete an [identity](https://www.ory.sh/docs/kratos/concepts/identity-user-model) credential by its type. You cannot delete password or code auth credentials through this API.
pub async fn delete_identity_credentials(
    configuration: &configuration::Configuration,
    id: &str,
    r#type: &str,
    identifier: Option<&str>,
) -> Result<(), Error<DeleteIdentityCredentialsError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("DELETE");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let id = crate::wasm_apis::urlencode(id);
    let possible_uri_len = (configuration.base_path.len() * 2)
        + "/admin/identities/".len()
        + id.len()
        + "/credentials/".len()
        + r#type.len()
        + "?identifier=".len();

    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities/");
    uri_str.push_str(&id);
    uri_str.push_str("/credentials/");
    uri_str.push_str(r#type);

    if let Some(ref str) = identifier {
        uri_str.push_str("?identifier=");
        uri_str.push_str(&str);
    }

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        Ok(())
    } else {
        let entity: Option<DeleteIdentityCredentialsError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// Calling this endpoint irrecoverably and permanently deletes and invalidates all sessions that belong to the given Identity.
pub async fn delete_identity_sessions(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<(), Error<DeleteIdentitySessionsError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("DELETE");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let id = crate::wasm_apis::urlencode(id);
    let possible_uri_len =
        configuration.base_path.len() + "/admin/identities/".len() + id.len() + "/sessions".len();

    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities/");
    uri_str.push_str(&id);
    uri_str.push_str("/sessions");

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        Ok(())
    } else {
        let entity: Option<DeleteIdentitySessionsError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// Calling this endpoint deactivates the specified session. Session data is not deleted.
pub async fn disable_session(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<(), Error<DisableSessionError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("DELETE");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let id = crate::wasm_apis::urlencode(id);
    let possible_uri_len = configuration.base_path.len() + "/admin/sessions/".len() + id.len();

    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/sessions/");
    uri_str.push_str(&id);

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        Ok(())
    } else {
        let entity: Option<DisableSessionError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// Calling this endpoint extends the given session ID. If `session.earliest_possible_extend` is set it will only extend the session after the specified time has passed.  This endpoint returns per default a 204 No Content response on success. Older Ory Network projects may return a 200 OK response with the session in the body. Returning the session as part of the response will be deprecated in the future and should not be relied upon.  This endpoint ignores consecutive requests to extend the same session and returns a 404 error in those scenarios. This endpoint also returns 404 errors if the session does not exist.  Retrieve the session ID from the `/sessions/whoami` endpoint / `toSession` SDK method.
pub async fn extend_session(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<models::Session, Error<ExtendSessionError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("PATCH");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let id = crate::wasm_apis::urlencode(id);
    let possible_uri_len =
        configuration.base_path.len() + "/admin/sessions/".len() + id.len() + "/extend".len();

    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/sessions/");
    uri_str.push_str(&id);
    uri_str.push_str("/extend");

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        content.into_serde().map_err(Error::from)
    } else {
        let entity: Option<ExtendSessionError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// Return an [identity](https://www.ory.sh/docs/kratos/concepts/identity-user-model) by its ID. You can optionally include credentials (e.g. social sign in connections) in the response by using the `include_credential` query parameter.
pub async fn get_identity(
    configuration: &configuration::Configuration,
    id: &str,
    include_credential: Option<Vec<String>>,
) -> Result<models::Identity, Error<GetIdentityError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("GET");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let id = crate::wasm_apis::urlencode(id);
    let possible_uri_len = configuration.base_path.len()
        + "/admin/identities/".len()
        + id.len()
        + "?include_credential=".len();

    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities/");
    uri_str.push_str(&id);

    if let Some(ref str_vec) = include_credential {
        uri_str.push_str("?include_credential=");
        let str = &str_vec
            .into_iter()
            .map(|p| p.to_string())
            .collect::<Vec<String>>()
            .join(",")
            .to_string();

        uri_str.push_str(str);
    }

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        content.into_serde().map_err(Error::from)
    } else {
        let entity: Option<GetIdentityError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// Return a specific identity schema.
pub async fn get_identity_schema(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<serde_json::Value, Error<GetIdentitySchemaError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("GET");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let id = crate::wasm_apis::urlencode(id);
    let possible_uri_len = configuration.base_path.len() + "/schemas/".len() + id.len();

    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/schemas/");
    uri_str.push_str(&id);

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        content.into_serde().map_err(Error::from)
    } else {
        let entity: Option<GetIdentitySchemaError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// This endpoint is useful for:  Getting a session object with all specified expandables that exist in an administrative context.
pub async fn get_session(
    configuration: &configuration::Configuration,
    id: &str,
    expand: Option<Vec<String>>,
) -> Result<models::Session, Error<GetSessionError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("GET");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let id = crate::wasm_apis::urlencode(id);
    let possible_uri_len =
        configuration.base_path.len() + "/admin/sessions/".len() + id.len() + "?expand=".len();

    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/sessions/");
    uri_str.push_str(&id);

    if let Some(ref str_vec) = expand {
        uri_str.push_str("?expand=");
        let str = &str_vec
            .into_iter()
            .map(|p| p.to_string())
            .collect::<Vec<String>>()
            .join(",")
            .to_string();

        uri_str.push_str(str);
    }

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        content.into_serde().map_err(Error::from)
    } else {
        let entity: Option<GetSessionError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// Lists all [identities](https://www.ory.sh/docs/kratos/concepts/identity-user-model) in the system. Note: filters cannot be combined.
pub async fn list_identities(
    configuration: &configuration::Configuration,
    per_page: Option<i64>,
    page: Option<i64>,
    page_size: Option<i64>,
    page_token: Option<&str>,
    consistency: Option<&str>,
    ids: Option<Vec<String>>,
    credentials_identifier: Option<&str>,
    preview_credentials_identifier_similar: Option<&str>,
    include_credential: Option<Vec<String>>,
    organization_id: Option<&str>,
) -> Result<Vec<models::Identity>, Error<ListIdentitiesError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("GET");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let possible_uri_len = configuration.base_path.len()
        + "/admin/identities".len()
        + "per_page".len()
        + i64::MAX.to_string().len()
        + "page".len()
        + i64::MAX.to_string().len()
        + "page_size".len()
        + i64::MAX.to_string().len()
        + "page_token".len()
        + "consistency".len()
        + "ids".len()
        + "credentials_identifier".len()
        + "preview_credentials_identifier_similar".len()
        + "include_credential".len()
        + "organization_id".len()
        + 20;
    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities");

    let mut is_first_query: bool = true;

    if let Some(ref str) = per_page {
        uri_str.add_query(&mut is_first_query, "per_page=", &str.to_string());
    }
    if let Some(ref str) = page {
        uri_str.add_query(&mut is_first_query, "page=", &str.to_string());
    }
    if let Some(ref str) = page_size {
        uri_str.add_query(&mut is_first_query, "page_size=", &str.to_string());
    }
    if let Some(ref str) = page_token {
        uri_str.add_query(&mut is_first_query, "page_token=", &str);
    };
    if let Some(ref str) = consistency {
        uri_str.add_query(&mut is_first_query, "consistency=", &str);
    };
    if let Some(ref str_vec) = ids {
        let str = &str_vec
            .into_iter()
            .map(|p| p.to_string())
            .collect::<Vec<String>>()
            .join(",")
            .to_string();

        uri_str.add_query(&mut is_first_query, "ids=", &str);
    }
    if let Some(ref str) = credentials_identifier {
        uri_str.add_query(&mut is_first_query, "credentials_identifier=", &str);
    }
    if let Some(ref str) = preview_credentials_identifier_similar {
        uri_str.add_query(
            &mut is_first_query,
            "preview_credentials_identifier_similar=",
            &str,
        );
    }
    if let Some(ref str_vec) = include_credential {
        uri_str.push_str("?include_credential=");
        let str = &str_vec
            .into_iter()
            .map(|p| p.to_string())
            .collect::<Vec<String>>()
            .join(",")
            .to_string();

        uri_str.push_str(str);
    }
    if let Some(ref str) = organization_id {
        uri_str.add_query(&mut is_first_query, "organization_id=", &str);
    }

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };

    req_builder.headers().set("Accept", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        content.into_serde().map_err(Error::from)
    } else {
        let entity: Option<ListIdentitiesError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// Returns a list of all identity schemas currently in use.
pub async fn list_identity_schemas(
    configuration: &configuration::Configuration,
    per_page: Option<i64>,
    page: Option<i64>,
    page_size: Option<i64>,
    page_token: Option<&str>,
) -> Result<Vec<models::IdentitySchemaContainer>, Error<ListIdentitySchemasError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("GET");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let possible_uri_len = configuration.base_path.len()
        + "/schemas".len()
        + "per_page".len()
        + i64::MAX.to_string().len()
        + "page".len()
        + i64::MAX.to_string().len()
        + "page_size".len()
        + i64::MAX.to_string().len()
        + "page_token".len()
        + 8;
    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/schemas");

    let mut is_first_query: bool = true;

    if let Some(ref str) = per_page {
        uri_str.add_query(&mut is_first_query, "per_page=", &str.to_string());
    }
    if let Some(ref str) = page {
        uri_str.add_query(&mut is_first_query, "page=", &str.to_string());
    }
    if let Some(ref str) = page_size {
        uri_str.add_query(&mut is_first_query, "page_size=", &str.to_string());
    }
    if let Some(ref str) = page_token {
        uri_str.add_query(&mut is_first_query, "page_token=", &str);
    };

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        content.into_serde().map_err(Error::from)
    } else {
        let entity: Option<ListIdentitySchemasError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// This endpoint returns all sessions that belong to the given Identity.
pub async fn list_identity_sessions(
    configuration: &configuration::Configuration,
    id: &str,
    per_page: Option<i64>,
    page: Option<i64>,
    page_size: Option<i64>,
    page_token: Option<&str>,
    active: Option<bool>,
) -> Result<Vec<models::Session>, Error<ListIdentitySessionsError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("GET");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let id = crate::wasm_apis::urlencode(id);
    let possible_uri_len = configuration.base_path.len()
        + "/admin/identities/".len()
        + id.len()
        + "/sessions".len()
        + "per_page".len()
        + i64::MAX.to_string().len()
        + "page".len()
        + i64::MAX.to_string().len()
        + "page_size".len()
        + i64::MAX.to_string().len()
        + "page_token".len()
        + "active".len()
        + 10;
    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities/");
    uri_str.push_str(&id);
    uri_str.push_str("/sessions");

    let mut is_first_query: bool = true;

    if let Some(ref str) = per_page {
        uri_str.add_query(&mut is_first_query, "per_page=", &str.to_string());
    }
    if let Some(ref str) = page {
        uri_str.add_query(&mut is_first_query, "page=", &str.to_string());
    }
    if let Some(ref str) = page_size {
        uri_str.add_query(&mut is_first_query, "page_size=", &str.to_string());
    }
    if let Some(ref str) = page_token {
        uri_str.add_query(&mut is_first_query, "page_token=", &str);
    };
    if let Some(ref str) = active {
        uri_str.add_query(&mut is_first_query, "active=", &str.to_string());
    }

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        content.into_serde().map_err(Error::from)
    } else {
        let entity: Option<ListIdentitySessionsError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// Listing all sessions that exist.
pub async fn list_sessions(
    configuration: &configuration::Configuration,
    page_size: Option<i64>,
    page_token: Option<&str>,
    active: Option<bool>,
    expand: Option<Vec<String>>,
) -> Result<Vec<models::Session>, Error<ListSessionsError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("GET");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let possible_uri_len = configuration.base_path.len()
        + "/admin/sessions".len()
        + "page_size".len()
        + i64::MAX.to_string().len()
        + "page_token".len()
        + "active".len()
        + "expand".len()
        + 13;
    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/sessions");

    let mut is_first_query: bool = true;

    if let Some(ref str) = page_size {
        uri_str.add_query(&mut is_first_query, "page_size=", &str.to_string());
    }
    if let Some(ref str) = page_token {
        uri_str.add_query(&mut is_first_query, "page_token=", &str);
    };
    if let Some(ref str) = active {
        uri_str.add_query(&mut is_first_query, "active=", &str.to_string());
    }
    if let Some(ref str_vec) = expand {
        let str = &str_vec
            .into_iter()
            .map(|p| p.to_string())
            .collect::<Vec<String>>()
            .join(",")
            .to_string();

        uri_str.add_query(&mut is_first_query, "expand=", &str);
    }

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };

    req_builder.headers().set("Accept", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        content.into_serde().map_err(Error::from)
    } else {
        let entity: Option<ListSessionsError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// Partially updates an [identity's](https://www.ory.sh/docs/kratos/concepts/identity-user-model) field using [JSON Patch](https://jsonpatch.com/). The fields `id`, `stateChangedAt` and `credentials` can not be updated using this method.
pub async fn patch_identity(
    configuration: &configuration::Configuration,
    id: &str,
    json_patch: Option<Vec<models::JsonPatch>>,
) -> Result<models::Identity, Error<PatchIdentityError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("PATCH");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let id = crate::wasm_apis::urlencode(id);
    let possible_uri_len = configuration.base_path.len() + "/admin/identities/".len() + id.len();
    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities/");
    uri_str.push_str(&id);

    client.set_body(&JsValue::from_serde(&json_patch)?);

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;
    req_builder
        .headers()
        .set("Content-Type", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        content.into_serde().map_err(Error::from)
    } else {
        let entity: Option<PatchIdentityError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// This endpoint updates an [identity](https://www.ory.sh/docs/kratos/concepts/identity-user-model). The full identity payload (except credentials) is expected. It is possible to update the identity's credentials as well.
pub async fn update_identity(
    configuration: &configuration::Configuration,
    id: &str,
    update_identity_body: Option<models::UpdateIdentityBody>,
) -> Result<models::Identity, Error<UpdateIdentityError>> {
    let configuration = configuration;

    let client = RequestInit::new();
    client.set_method("PUT");
    client.set_mode(RequestMode::Cors);
    client.set_credentials(RequestCredentials::SameOrigin);

    let id = crate::wasm_apis::urlencode(id);
    let possible_uri_len = configuration.base_path.len() + "/admin/identities/".len() + id.len();
    let mut uri_str = String::with_capacity(possible_uri_len);

    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities/");
    uri_str.push_str(&id);

    client.set_body(&JsValue::from_serde(&update_identity_body)?);

    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;
    req_builder
        .headers()
        .set("Content-Type", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        content.into_serde().map_err(Error::from)
    } else {
        let entity: Option<UpdateIdentityError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}
