/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more.
 *
 * The version of the OpenAPI document: v26.2.0
 * Contact: office@ory.sh
 * Generated by: https://openapi-generator.tech (via tools/regen-fetch-apis, see task #23)
 */

use super::{AddQuery, Error, configuration};
use crate::models;
use gloo_utils::format::JsValueSerdeExt;
use serde::{Deserialize, Serialize};
use wasm_bindgen::prelude::*;

/// struct for typed errors of method [`batch_patch_identities`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BatchPatchIdentitiesError {
    Status400(models::ErrorGeneric),
    Status409(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_identity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateIdentityError {
    Status400(models::ErrorGeneric),
    Status409(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_recovery_code_for_identity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateRecoveryCodeForIdentityError {
    Status400(models::ErrorGeneric),
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_recovery_link_for_identity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateRecoveryLinkForIdentityError {
    Status400(models::ErrorGeneric),
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_identity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteIdentityError {
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_identity_credentials`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteIdentityCredentialsError {
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_identity_sessions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteIdentitySessionsError {
    Status400(models::ErrorGeneric),
    Status401(models::ErrorGeneric),
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`disable_session`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DisableSessionError {
    Status400(models::ErrorGeneric),
    Status401(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`extend_session`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExtendSessionError {
    Status400(models::ErrorGeneric),
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_identity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetIdentityError {
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_identity_by_external_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetIdentityByExternalIdError {
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_identity_schema`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetIdentitySchemaError {
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_session`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSessionError {
    Status400(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_identities`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListIdentitiesError {
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_identity_schemas`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListIdentitySchemasError {
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_identity_sessions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListIdentitySessionsError {
    Status400(models::ErrorGeneric),
    Status404(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_sessions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListSessionsError {
    Status400(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`patch_identity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PatchIdentityError {
    Status400(models::ErrorGeneric),
    Status404(models::ErrorGeneric),
    Status409(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_identity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateIdentityError {
    Status400(models::ErrorGeneric),
    Status404(models::ErrorGeneric),
    Status409(models::ErrorGeneric),
    DefaultResponse(models::ErrorGeneric),
    UnknownValue(serde_json::Value),
}

/// Creates multiple [identities](https://www.ory.com/docs/kratos/concepts/identity-user-model).  You can also use this endpoint to [import credentials](https://www.ory.com/docs/kratos/manage-identities/import-user-accounts-identities), including passwords, social sign-in settings, and multi-factor authentication methods.  If the patch includes hashed passwords you can import up to 1,000 identities per request.  If the patch includes at least one plaintext password you can import up to 200 identities per request.  Avoid importing large batches with plaintext passwords. They can cause timeouts as the passwords need to be hashed before they are stored.  If at least one identity is imported successfully, the response status is 200 OK. If all imports fail, the response is one of the following 4xx errors: 400 Bad Request: The request payload is invalid or improperly formatted. 409 Conflict: Duplicate identities or conflicting data were detected.  If you get a 504 Gateway Timeout: Reduce the batch size Avoid duplicate identities Pre-hash passwords with BCrypt  If the issue persists, contact support.
pub async fn batch_patch_identities(
    configuration: &configuration::Configuration,
    patch_identities_body: Option<models::PatchIdentitiesBody>,
) -> Result<models::BatchPatchIdentitiesResponse, Error<BatchPatchIdentitiesError>> {
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities");
    let client = web_sys::RequestInit::new();
    client.set_method("PATCH");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    client.set_body(&JsValue::from_serde(&patch_identities_body)?);
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };
    req_builder.headers().set("Accept", "application/json")?;
    req_builder
        .headers()
        .set("Content-Type", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_response(resp).await
}

/// Create an [identity](https://www.ory.sh/docs/kratos/concepts/identity-user-model).  This endpoint can also be used to [import credentials](https://www.ory.sh/docs/kratos/manage-identities/import-user-accounts-identities) for instance passwords, social sign in configurations or multifactor methods.
pub async fn create_identity(
    configuration: &configuration::Configuration,
    create_identity_body: Option<models::CreateIdentityBody>,
) -> Result<models::Identity, Error<CreateIdentityError>> {
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities");
    let client = web_sys::RequestInit::new();
    client.set_method("POST");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    client.set_body(&JsValue::from_serde(&create_identity_body)?);
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };
    req_builder.headers().set("Accept", "application/json")?;
    req_builder
        .headers()
        .set("Content-Type", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_response(resp).await
}

/// This endpoint creates a recovery code which should be given to the user in order for them to recover (or activate) their account.
pub async fn create_recovery_code_for_identity(
    configuration: &configuration::Configuration,
    create_recovery_code_for_identity_body: Option<models::CreateRecoveryCodeForIdentityBody>,
) -> Result<models::RecoveryCodeForIdentity, Error<CreateRecoveryCodeForIdentityError>> {
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/recovery/code");
    let client = web_sys::RequestInit::new();
    client.set_method("POST");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    client.set_body(&JsValue::from_serde(
        &create_recovery_code_for_identity_body,
    )?);
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };
    req_builder.headers().set("Accept", "application/json")?;
    req_builder
        .headers()
        .set("Content-Type", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_response(resp).await
}

/// This endpoint creates a recovery link which should be given to the user in order for them to recover (or activate) their account.
pub async fn create_recovery_link_for_identity(
    configuration: &configuration::Configuration,
    return_to: Option<&str>,
    create_recovery_link_for_identity_body: Option<models::CreateRecoveryLinkForIdentityBody>,
) -> Result<models::RecoveryLinkForIdentity, Error<CreateRecoveryLinkForIdentityError>> {
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/recovery/link");
    let client = web_sys::RequestInit::new();
    client.set_method("POST");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    client.set_body(&JsValue::from_serde(
        &create_recovery_link_for_identity_body,
    )?);
    let mut is_first_query: bool = true;
    if let Some(ref str) = return_to {
        uri_str.add_query(&mut is_first_query, "return_to=", &str.to_string());
    }
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };
    req_builder.headers().set("Accept", "application/json")?;
    req_builder
        .headers()
        .set("Content-Type", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_response(resp).await
}

/// Calling this endpoint irrecoverably and permanently deletes the [identity](https://www.ory.sh/docs/kratos/concepts/identity-user-model) given its ID. This action can not be undone. This endpoint returns 204 when the identity was deleted or 404 if the identity was not found.
pub async fn delete_identity(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<(), Error<DeleteIdentityError>> {
    let id = crate::wasm_apis::urlencode(id);
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities/");
    uri_str.push_str(&id);
    let client = web_sys::RequestInit::new();
    client.set_method("DELETE");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };
    req_builder.headers().set("Accept", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_empty_response(resp).await
}

/// Delete an [identity](https://www.ory.sh/docs/kratos/concepts/identity-user-model) credential by its type. You cannot delete passkeys or code auth credentials through this API.
pub async fn delete_identity_credentials(
    configuration: &configuration::Configuration,
    id: &str,
    r#type: &str,
    identifier: Option<&str>,
) -> Result<(), Error<DeleteIdentityCredentialsError>> {
    let id = crate::wasm_apis::urlencode(id);
    let r#type = crate::wasm_apis::urlencode(r#type);
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities/");
    uri_str.push_str(&id);
    uri_str.push_str("/credentials/");
    uri_str.push_str(&r#type);
    let client = web_sys::RequestInit::new();
    client.set_method("DELETE");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    let mut is_first_query: bool = true;
    if let Some(ref str) = identifier {
        uri_str.add_query(&mut is_first_query, "identifier=", &str.to_string());
    }
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };
    req_builder.headers().set("Accept", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_empty_response(resp).await
}

/// Calling this endpoint irrecoverably and permanently deletes and invalidates all sessions that belong to the given Identity.
pub async fn delete_identity_sessions(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<(), Error<DeleteIdentitySessionsError>> {
    let id = crate::wasm_apis::urlencode(id);
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities/");
    uri_str.push_str(&id);
    uri_str.push_str("/sessions");
    let client = web_sys::RequestInit::new();
    client.set_method("DELETE");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };
    req_builder.headers().set("Accept", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_empty_response(resp).await
}

/// Calling this endpoint deactivates the specified session. Session data is not deleted.
pub async fn disable_session(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<(), Error<DisableSessionError>> {
    let id = crate::wasm_apis::urlencode(id);
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/sessions/");
    uri_str.push_str(&id);
    let client = web_sys::RequestInit::new();
    client.set_method("DELETE");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };
    req_builder.headers().set("Accept", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_empty_response(resp).await
}

/// Calling this endpoint extends the given session ID. If `session.earliest_possible_extend` is set it will only extend the session after the specified time has passed.  This endpoint returns per default a 204 No Content response on success. Older Ory Network projects may return a 200 OK response with the session in the body. Returning the session as part of the response will be deprecated in the future and should not be relied upon.  This endpoint ignores consecutive requests to extend the same session and returns a 404 error in those scenarios. This endpoint also returns 404 errors if the session does not exist.  Retrieve the session ID from the `/sessions/whoami` endpoint / `toSession` SDK method.
pub async fn extend_session(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<models::Session, Error<ExtendSessionError>> {
    let id = crate::wasm_apis::urlencode(id);
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/sessions/");
    uri_str.push_str(&id);
    uri_str.push_str("/extend");
    let client = web_sys::RequestInit::new();
    client.set_method("PATCH");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };
    req_builder.headers().set("Accept", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_response(resp).await
}

/// Return an [identity](https://www.ory.sh/docs/kratos/concepts/identity-user-model) by its ID. You can optionally include credentials (e.g. social sign in connections) in the response by using the `include_credential` query parameter.
pub async fn get_identity(
    configuration: &configuration::Configuration,
    id: &str,
    include_credential: Option<Vec<String>>,
) -> Result<models::Identity, Error<GetIdentityError>> {
    let id = crate::wasm_apis::urlencode(id);
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities/");
    uri_str.push_str(&id);
    let client = web_sys::RequestInit::new();
    client.set_method("GET");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    let mut is_first_query: bool = true;
    if let Some(ref str_vec) = include_credential {
        let joined = str_vec
            .into_iter()
            .map(|p| p.to_string())
            .collect::<Vec<String>>()
            .join("&include_credential=")
            .to_string();
        uri_str.add_query(&mut is_first_query, "include_credential=", &joined);
    }
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };
    req_builder.headers().set("Accept", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_response(resp).await
}

/// Return an [identity](https://www.ory.sh/docs/kratos/concepts/identity-user-model) by its external ID. You can optionally include credentials (e.g. social sign in connections) in the response by using the `include_credential` query parameter.
pub async fn get_identity_by_external_id(
    configuration: &configuration::Configuration,
    external_id: &str,
    include_credential: Option<Vec<String>>,
) -> Result<models::Identity, Error<GetIdentityByExternalIdError>> {
    let external_id = crate::wasm_apis::urlencode(external_id);
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities/by/external/");
    uri_str.push_str(&external_id);
    let client = web_sys::RequestInit::new();
    client.set_method("GET");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    let mut is_first_query: bool = true;
    if let Some(ref str_vec) = include_credential {
        let joined = str_vec
            .into_iter()
            .map(|p| p.to_string())
            .collect::<Vec<String>>()
            .join("&include_credential=")
            .to_string();
        uri_str.add_query(&mut is_first_query, "include_credential=", &joined);
    }
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };
    req_builder.headers().set("Accept", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_response(resp).await
}

/// Return a specific identity schema.
pub async fn get_identity_schema(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<serde_json::Value, Error<GetIdentitySchemaError>> {
    let id = crate::wasm_apis::urlencode(id);
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/schemas/");
    uri_str.push_str(&id);
    let client = web_sys::RequestInit::new();
    client.set_method("GET");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    req_builder.headers().set("Accept", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_response(resp).await
}

/// This endpoint is useful for:  Getting a session object with all specified expandables that exist in an administrative context.
pub async fn get_session(
    configuration: &configuration::Configuration,
    id: &str,
    expand: Option<Vec<String>>,
) -> Result<models::Session, Error<GetSessionError>> {
    let id = crate::wasm_apis::urlencode(id);
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/sessions/");
    uri_str.push_str(&id);
    let client = web_sys::RequestInit::new();
    client.set_method("GET");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    let mut is_first_query: bool = true;
    if let Some(ref str_vec) = expand {
        let joined = str_vec
            .into_iter()
            .map(|p| p.to_string())
            .collect::<Vec<String>>()
            .join("&expand=")
            .to_string();
        uri_str.add_query(&mut is_first_query, "expand=", &joined);
    }
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };
    req_builder.headers().set("Accept", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_response(resp).await
}

/// Lists all [identities](https://www.ory.sh/docs/kratos/concepts/identity-user-model) in the system. Note: filters cannot be combined.
pub async fn list_identities(
    configuration: &configuration::Configuration,
    per_page: Option<i64>,
    page: Option<i64>,
    page_size: Option<i64>,
    page_token: Option<&str>,
    consistency: Option<&str>,
    ids: Option<Vec<String>>,
    credentials_identifier: Option<&str>,
    preview_credentials_identifier_similar: Option<&str>,
    include_credential: Option<Vec<String>>,
    organization_id: Option<&str>,
) -> Result<Vec<models::Identity>, Error<ListIdentitiesError>> {
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities");
    let client = web_sys::RequestInit::new();
    client.set_method("GET");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    let mut is_first_query: bool = true;
    if let Some(ref str) = per_page {
        uri_str.add_query(&mut is_first_query, "per_page=", &str.to_string());
    }
    if let Some(ref str) = page {
        uri_str.add_query(&mut is_first_query, "page=", &str.to_string());
    }
    if let Some(ref str) = page_size {
        uri_str.add_query(&mut is_first_query, "page_size=", &str.to_string());
    }
    if let Some(ref str) = page_token {
        uri_str.add_query(&mut is_first_query, "page_token=", &str.to_string());
    }
    if let Some(ref str) = consistency {
        uri_str.add_query(&mut is_first_query, "consistency=", &str.to_string());
    }
    if let Some(ref str_vec) = ids {
        let joined = str_vec
            .into_iter()
            .map(|p| p.to_string())
            .collect::<Vec<String>>()
            .join("&ids=")
            .to_string();
        uri_str.add_query(&mut is_first_query, "ids=", &joined);
    }
    if let Some(ref str) = credentials_identifier {
        uri_str.add_query(
            &mut is_first_query,
            "credentials_identifier=",
            &str.to_string(),
        );
    }
    if let Some(ref str) = preview_credentials_identifier_similar {
        uri_str.add_query(
            &mut is_first_query,
            "preview_credentials_identifier_similar=",
            &str.to_string(),
        );
    }
    if let Some(ref str_vec) = include_credential {
        let joined = str_vec
            .into_iter()
            .map(|p| p.to_string())
            .collect::<Vec<String>>()
            .join("&include_credential=")
            .to_string();
        uri_str.add_query(&mut is_first_query, "include_credential=", &joined);
    }
    if let Some(ref str) = organization_id {
        uri_str.add_query(&mut is_first_query, "organization_id=", &str.to_string());
    }
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };
    req_builder.headers().set("Accept", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_response(resp).await
}

/// Returns a list of all identity schemas currently in use.
pub async fn list_identity_schemas(
    configuration: &configuration::Configuration,
    per_page: Option<i64>,
    page: Option<i64>,
    page_size: Option<i64>,
    page_token: Option<&str>,
) -> Result<Vec<models::IdentitySchemaContainer>, Error<ListIdentitySchemasError>> {
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/schemas");
    let client = web_sys::RequestInit::new();
    client.set_method("GET");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    let mut is_first_query: bool = true;
    if let Some(ref str) = per_page {
        uri_str.add_query(&mut is_first_query, "per_page=", &str.to_string());
    }
    if let Some(ref str) = page {
        uri_str.add_query(&mut is_first_query, "page=", &str.to_string());
    }
    if let Some(ref str) = page_size {
        uri_str.add_query(&mut is_first_query, "page_size=", &str.to_string());
    }
    if let Some(ref str) = page_token {
        uri_str.add_query(&mut is_first_query, "page_token=", &str.to_string());
    }
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    req_builder.headers().set("Accept", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_response(resp).await
}

/// This endpoint returns all sessions that belong to the given Identity.
pub async fn list_identity_sessions(
    configuration: &configuration::Configuration,
    id: &str,
    per_page: Option<i64>,
    page: Option<i64>,
    page_size: Option<i64>,
    page_token: Option<&str>,
    active: Option<bool>,
) -> Result<Vec<models::Session>, Error<ListIdentitySessionsError>> {
    let id = crate::wasm_apis::urlencode(id);
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities/");
    uri_str.push_str(&id);
    uri_str.push_str("/sessions");
    let client = web_sys::RequestInit::new();
    client.set_method("GET");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    let mut is_first_query: bool = true;
    if let Some(ref str) = per_page {
        uri_str.add_query(&mut is_first_query, "per_page=", &str.to_string());
    }
    if let Some(ref str) = page {
        uri_str.add_query(&mut is_first_query, "page=", &str.to_string());
    }
    if let Some(ref str) = page_size {
        uri_str.add_query(&mut is_first_query, "page_size=", &str.to_string());
    }
    if let Some(ref str) = page_token {
        uri_str.add_query(&mut is_first_query, "page_token=", &str.to_string());
    }
    if let Some(ref str) = active {
        uri_str.add_query(&mut is_first_query, "active=", &str.to_string());
    }
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };
    req_builder.headers().set("Accept", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_response(resp).await
}

/// Listing all sessions that exist.
pub async fn list_sessions(
    configuration: &configuration::Configuration,
    page_size: Option<i64>,
    page_token: Option<&str>,
    active: Option<bool>,
    expand: Option<Vec<String>>,
) -> Result<Vec<models::Session>, Error<ListSessionsError>> {
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/sessions");
    let client = web_sys::RequestInit::new();
    client.set_method("GET");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    let mut is_first_query: bool = true;
    if let Some(ref str) = page_size {
        uri_str.add_query(&mut is_first_query, "page_size=", &str.to_string());
    }
    if let Some(ref str) = page_token {
        uri_str.add_query(&mut is_first_query, "page_token=", &str.to_string());
    }
    if let Some(ref str) = active {
        uri_str.add_query(&mut is_first_query, "active=", &str.to_string());
    }
    if let Some(ref str_vec) = expand {
        let joined = str_vec
            .into_iter()
            .map(|p| p.to_string())
            .collect::<Vec<String>>()
            .join("&expand=")
            .to_string();
        uri_str.add_query(&mut is_first_query, "expand=", &joined);
    }
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };
    req_builder.headers().set("Accept", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_response(resp).await
}

/// Partially updates an [identity's](https://www.ory.sh/docs/kratos/concepts/identity-user-model) field using [JSON Patch](https://jsonpatch.com/). The fields `id`, `stateChangedAt` and `credentials` can not be updated using this method.
pub async fn patch_identity(
    configuration: &configuration::Configuration,
    id: &str,
    json_patch: Option<Vec<models::JsonPatch>>,
) -> Result<models::Identity, Error<PatchIdentityError>> {
    let id = crate::wasm_apis::urlencode(id);
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities/");
    uri_str.push_str(&id);
    let client = web_sys::RequestInit::new();
    client.set_method("PATCH");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    client.set_body(&JsValue::from_serde(&json_patch)?);
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };
    req_builder.headers().set("Accept", "application/json")?;
    req_builder
        .headers()
        .set("Content-Type", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_response(resp).await
}

/// This endpoint updates an [identity](https://www.ory.sh/docs/kratos/concepts/identity-user-model). The full identity payload, except credentials, is expected. For partial updates, use the [patchIdentity](https://www.ory.sh/docs/reference/api#tag/identity/operation/patchIdentity) operation.  A credential can be provided via the `credentials` field in the request body. If provided, the credentials will be imported and added to the existing credentials of the identity.
pub async fn update_identity(
    configuration: &configuration::Configuration,
    id: &str,
    update_identity_body: Option<models::UpdateIdentityBody>,
) -> Result<models::Identity, Error<UpdateIdentityError>> {
    let id = crate::wasm_apis::urlencode(id);
    let mut uri_str = String::new();
    uri_str.push_str(&configuration.base_path);
    uri_str.push_str("/admin/identities/");
    uri_str.push_str(&id);
    let client = web_sys::RequestInit::new();
    client.set_method("PUT");
    client.set_mode(web_sys::RequestMode::Cors);
    client.set_credentials(web_sys::RequestCredentials::Include);
    client.set_body(&JsValue::from_serde(&update_identity_body)?);
    let req_builder = web_sys::Request::new_with_str_and_init(&uri_str, &client)?;
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder.headers().set("Authorization", &value)?;
    };
    req_builder.headers().set("Accept", "application/json")?;
    req_builder
        .headers()
        .set("Content-Type", "application/json")?;
    let req = wasm_bindgen_futures::JsFuture::from(
        web_sys::window()
            .expect("Failed to get Window object")
            .fetch_with_request(&req_builder),
    )
    .await?;
    assert!(req.is_instance_of::<web_sys::Response>());
    let resp: web_sys::Response = req
        .dyn_into()
        .expect("Failed to dynamically cast JsFuture into Response");
    super::handle_response(resp).await
}
