/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more.
 *
 * The version of the OpenAPI document: v1.3.8
 * Contact: office@ory.sh
 * Generated by: https://openapi-generator.tech
 */

use super::{Error, configuration};
use crate::{models, wasm_apis::ResponseContent};
use gloo_utils::format::JsValueSerdeExt;
use serde::{Deserialize, Serialize};
use wasm_bindgen::prelude::*;
use wasm_bindgen_futures::JsFuture;
use web_sys::{Request, RequestInit, RequestMode, Response};

/// struct for typed errors of method [`get_version`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVersionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`is_alive`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IsAliveError {
    DefaultResponse(String),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`is_ready`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IsReadyError {
    Status503(models::IsReady503Response),
    DefaultResponse(String),
    UnknownValue(serde_json::Value),
}

/// This endpoint returns the version of Ory Kratos.  If the service supports TLS Edge Termination, this endpoint does not require the `X-Forwarded-Proto` header to be set.  Be aware that if you are running multiple nodes of this service, the version will never refer to the cluster state, only to a single instance.
pub async fn get_version(
    configuration: &configuration::Configuration,
) -> Result<models::GetVersion200Response, Error<GetVersionError>> {
    let client = RequestInit::new();
    client.set_method("GET");
    client.set_mode(RequestMode::Cors);

    let uri_str = format!("{}/version", configuration.base_path);
    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        content.into_serde().map_err(Error::from)
    } else {
        let entity: Option<GetVersionError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// This endpoint returns a HTTP 200 status code when Ory Kratos is accepting incoming HTTP requests. This status does currently not include checks whether the database connection is working.  If the service supports TLS Edge Termination, this endpoint does not require the `X-Forwarded-Proto` header to be set.  Be aware that if you are running multiple nodes of this service, the health status will never refer to the cluster state, only to a single instance.
pub async fn is_alive(
    configuration: &configuration::Configuration,
) -> Result<models::IsAlive200Response, Error<IsAliveError>> {
    let client = RequestInit::new();
    client.set_method("GET");
    client.set_mode(RequestMode::Cors);

    let uri_str = format!("{}/health/ready", configuration.base_path);
    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        content.into_serde().map_err(Error::from)
    } else {
        let entity: Option<IsAliveError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}

/// This endpoint returns a HTTP 200 status code when Ory Kratos is up running and the environment dependencies (e.g. the database) are responsive as well.  If the service supports TLS Edge Termination, this endpoint does not require the `X-Forwarded-Proto` header to be set.  Be aware that if you are running multiple nodes of Ory Kratos, the health status will never refer to the cluster state, only to a single instance.
pub async fn is_ready(
    configuration: &configuration::Configuration,
) -> Result<models::IsAlive200Response, Error<IsReadyError>> {
    let client = RequestInit::new();
    client.set_method("GET");
    client.set_mode(RequestMode::Cors);

    let uri_str = format!("{}/health/ready", configuration.base_path);
    let req_builder = Request::new_with_str_and_init(&uri_str, &client)?;

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder.headers().set("USER_AGENT", user_agent)?;
    }

    req_builder.headers().set("Accept", "application/json")?;

    let req = JsFuture::from(web_sys::window().unwrap().fetch_with_request(&req_builder)).await?;

    assert!(req.is_instance_of::<Response>());
    let resp: Response = req.dyn_into().unwrap();

    let status = resp.status();
    let content = JsFuture::from(resp.json()?).await?;

    if !(400..600).contains(&status) {
        content.into_serde().map_err(Error::from)
    } else {
        let entity: Option<IsReadyError> = content.into_serde().ok();
        let error = ResponseContent {
            status: status,
            content: if content.is_undefined() {
                String::from("null")
            } else {
                web_sys::js_sys::JSON::stringify(&content)
                    .map(String::from)
                    .unwrap_throw()
            },
            entity: entity,
        };
        Err(Error::ResponseError(error))
    }
}
