[package]
name = "ory-kratos-client"
version = "1.3.8"
authors = ["office@ory.sh"]
description = "OpenAPI API client for Ory Kratos, Ory's central identity management solution with hardened authentication, MFA, FIDO2, TOTP, WebAuthn, SSO, profile management, and more."
license = "Apache-2.0"
edition = "2021"
resolver = "2"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_with = { version = "^3.8", default-features = false, features = ["base64", "std", "macros"] }
serde_json = "^1.0"
url = "^2.5"

[target.'cfg(target_family = "wasm")'.dependencies]
gloo-utils = { version = "0.1", features = ["serde"] }
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.77", features = ["Headers", "Request", "RequestInit", "RequestMode", "Response", "Window", "RequestCredentials"] }
uuid = { version = "^1.8", features = ["serde", "v4", "js"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
flate2 = { version = "1.0.24", features = ["zlib-ng"], default-features = false }
reqwest = { version = "^0.12", features = ["json", "multipart"] }
uuid = { version = "^1.8", features = ["serde", "v4"] }
