/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more.
 *
 * The version of the OpenAPI document: v25.4.0
 * Contact: office@ory.sh
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{models, worker_apis::ResponseContent};
use serde::{Deserialize, Serialize, de::Error as _};
use wasm_bindgen::prelude::*;
use worker::{Fetch, Headers, Method, Request, RequestInit, Response};

/// struct for typed errors of method [`get_version`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVersionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`is_alive`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IsAliveError {
    DefaultResponse(String),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`is_ready`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IsReadyError {
    Status503(models::IsReady503Response),
    DefaultResponse(String),
    UnknownValue(serde_json::Value),
}

/// This endpoint returns the version of Ory Kratos.  If the service supports TLS Edge Termination, this endpoint does not require the `X-Forwarded-Proto` header to be set.  Be aware that if you are running multiple nodes of this service, the version will never refer to the cluster state, only to a single instance.
pub async fn get_version(
    configuration: &configuration::Configuration,
) -> Result<models::GetVersion200Response, Error<GetVersionError>> {
    let uri_str = format!("{}/version", configuration.base_path);
    let mut headers = Headers::new();

    if let Some(ref user_agent) = configuration.user_agent {
        headers.append("USER_AGENT", user_agent)?;
    }

    headers.append("Accept", "application/json")?;

    if let Some(ref cors) = configuration.cors {
        cors.apply_headers(&mut headers)?;
    }

    let mut req_builder = RequestInit::new();
    req_builder.with_method(Method::Get);
    req_builder.with_headers(headers);

    let req = Request::new_with_init(&uri_str, &req_builder)?;

    let mut resp = Fetch::Request(req).send().await?;
    let status = resp.status_code();
    let content_type = super::ContentType::from(&resp);

    if !(400..600).contains(&status) {
        match content_type {
            ContentType::Json => resp.json().await.map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::GetVersion200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::GetVersion200Response`"
                ))));
            }
            ContentType::Missing => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received response that is missing `content-type` header"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetVersionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content: if content.is_empty() {
                String::from("null")
            } else {
                content
            },
            entity,
        }))
    }
}

/// This endpoint returns a HTTP 200 status code when Ory Kratos is accepting incoming HTTP requests. This status does currently not include checks whether the database connection is working.  If the service supports TLS Edge Termination, this endpoint does not require the `X-Forwarded-Proto` header to be set.  Be aware that if you are running multiple nodes of this service, the health status will never refer to the cluster state, only to a single instance.
pub async fn is_alive(
    configuration: &configuration::Configuration,
) -> Result<models::IsAlive200Response, Error<IsAliveError>> {
    let uri_str = format!("{}/health/ready", configuration.base_path);
    let mut headers = Headers::new();

    if let Some(ref user_agent) = configuration.user_agent {
        headers.append("USER_AGENT", user_agent)?;
    }

    headers.append("Accept", "application/json")?;

    if let Some(ref cors) = configuration.cors {
        cors.apply_headers(&mut headers)?;
    }

    let mut req_builder = RequestInit::new();
    req_builder.with_method(Method::Get);
    req_builder.with_headers(headers);

    let req = Request::new_with_init(&uri_str, &req_builder)?;

    let mut resp = Fetch::Request(req).send().await?;
    let status = resp.status_code();
    let content_type = super::ContentType::from(&resp);

    if !(400..600).contains(&status) {
        match content_type {
            ContentType::Json => resp.json().await.map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::IsAlive200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::IsAlive200Response`"
                ))));
            }
            ContentType::Missing => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received response that is missing `content-type` header"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<IsAliveError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content: if content.is_empty() {
                String::from("null")
            } else {
                content
            },
            entity,
        }))
    }
}

/// This endpoint returns a HTTP 200 status code when Ory Kratos is up running and the environment dependencies (e.g. the database) are responsive as well.  If the service supports TLS Edge Termination, this endpoint does not require the `X-Forwarded-Proto` header to be set.  Be aware that if you are running multiple nodes of Ory Kratos, the health status will never refer to the cluster state, only to a single instance.
pub async fn is_ready(
    configuration: &configuration::Configuration,
) -> Result<models::IsAlive200Response, Error<IsReadyError>> {
    let uri_str = format!("{}/health/ready", configuration.base_path);
    let mut headers = Headers::new();

    if let Some(ref user_agent) = configuration.user_agent {
        headers.append("USER_AGENT", user_agent)?;
    }

    headers.append("Accept", "application/json")?;

    if let Some(ref cors) = configuration.cors {
        cors.apply_headers(&mut headers)?;
    }

    let mut req_builder = RequestInit::new();
    req_builder.with_method(Method::Get);
    req_builder.with_headers(headers);

    let req = Request::new_with_init(&uri_str, &req_builder)?;

    let mut resp = Fetch::Request(req).send().await?;
    let status = resp.status_code();
    let content_type = super::ContentType::from(&resp);

    if !(400..600).contains(&status) {
        match content_type {
            ContentType::Json => resp.json().await.map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::IsAlive200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::IsAlive200Response`"
                ))));
            }
            ContentType::Missing => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received response that is missing `content-type` header"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<IsReadyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content: if content.is_empty() {
                String::from("null")
            } else {
                content
            },
            entity,
        }))
    }
}
